# This is a sample deployment manifest file for a simple web application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app-devops-project
  labels:
    app: go-web-app-devops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-app-devops-project
  template:
    metadata:
      labels:
        app: go-web-app-devops-project
    spec:
      containers:
      - name: go-web-app-devops-project
        image: durolusegun/go-web-app-devops-project:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080